Update Ecoregeling Fase 2
AgroCares/BedrijfsBodemWaterPlanCalculator pull request #70
Opened 2023-01-18 13:05 UTC by astridberndsen

Updates as requested for Ecoregeling Fase 2:

The CSV files for internal tables bbwp_measures and er_measures are updated (reduce variants of EG20 from 18 to 6). Checked whether the eco brp codes occur in pandex.

Bbwp_measures table has extra category `alles` in column `categories` for each Ecoregeling measure.

Measures EB18 and EB19 are now field level measures and therefore transferred from er_croprotation to er_meas_scores for calculations

Calculation of crop diversification index (EB10) is now based on the unique crops to which EB10 applies. The calculation of non productive area for EG20 is based on 100% nature area fields instead of 1-3%, 3-5% or >5% nature areas within fields.

The lower input level for `B_AREA` changed from 0 into 10 (issue #BBWP-60)

2023-01-18 14:25 UTC, gerardhros commented on DESCRIPTION
> +Version: 0.10.19
by adding the ecoregeling i would have expected to move to a new release. is somehow not done yet.

the third position is usually used for small fixes, the second one for bigger updates (additional features) and the first one is for real upgrades adding new functionalities (and sometimes breaking changes).

you might do that here

2023-01-18 14:27 UTC, gerardhros commented on R/er_croprotation.R
> +  dt.field[is.na(eco_app),eco_app := 1]
this is a strange duplication. if you replace all NA with zero why checking/replacing with 1 afterwards?

2023-01-18 15:13 UTC, TessaNMI commented on R/er_croprotation.R
> +  dt.field[is.na(eco_app),eco_app := 1]
in eco-app it is was neccesary to add a column eco_app.  Maybe?

2023-01-18 15:20 UTC, astridberndsen commented on R/er_croprotation.R
> +  dt.field[is.na(eco_app),eco_app := 1]
This is a strange duplication indeed. I removed the last line.

2023-01-18 15:26 UTC, astridberndsen commented on DESCRIPTION
> +Version: 0.10.19
I changed the version into 0.11.0.

2023-01-18 15:30 UTC, TessaNMI approved these changes
will leave the final call to gerard

2023-01-18 19:12 UTC, gerardhros commented on DESCRIPTION
> +Version: 0.10.19
if you finilize the latest update for ER, please boost version to 1.0.0

2023-01-18 19:21 UTC, gerardhros commented on R/er_farm_aim.R
> +  checkmate::assert_numeric(B_AREA, lower = 10, upper = bbwp_parms[code == "B_AREA", value_max], len = arg.length)
did you by purpose overwrite the defaults from bbwp_parms? Its ok for the moment.
i see that this is not consistently done in the package, so might become a new task to be done in another branch

2023-01-18 19:26 UTC, gerardhros commented on R/er_meas_scores.R
> +    dt[grepl('^EG20',eco_id) & B_AREA_REL > 7 & B_AREA_REL < 9 & er_total > 0, c(cols.sel) := Map('+',mget(cols.sel),cols.ad1)]
what happens when B_AREA_REL == 9?

2023-01-18 19:38 UTC, gerardhros commented on tests/testthat/test-bbwp.R
>        tolerance = 0.01)
what is the reason that the BBWP score has to be adapted whereas only changes has been done in the Ecoregeling scripts. Please check if you made by accident a change in the bbwp scoring for BBWP scoring.

2023-01-18 19:41 UTC, gerardhros commented on tests/testthat/test-bbwp_field_scores.R
> +      S_BBWP_NUE = c(99,53,100),
here too. what is the reason that BBWP field scores are altered when you only update Ecoregeling scripts and methods?

2023-01-18 19:42 UTC, gerardhros requested changes
nice update.
see a few comments to be checked and evaluated.

2023-01-20 08:45 UTC, astridberndsen commented on R/er_meas_scores.R
> +    dt[grepl('^EG20',eco_id) & B_AREA_REL > 7 & B_AREA_REL < 9 & er_total > 0, c(cols.sel) := Map('+',mget(cols.sel),cols.ad1)]
I updated the calculations. Now B_AREA_REL <= 5.

2023-01-20 08:59 UTC, astridberndsen commented on R/er_farm_aim.R
> +  checkmate::assert_numeric(B_AREA, lower = 10, upper = bbwp_parms[code == "B_AREA", value_max], len = arg.length)
Plots smaller than 10 m2 generate errors in the ecoregeling calculations because B_AREA is in m2 but points are given and calculated in ha. It rarely occurs that plots of 10 m2 are used as input, but to be sure errors are prevented the lower boundary is set to 10. For now, I leave it like this and I will create a new branch later to do this consistently through the package.

2023-01-20 09:19 UTC, astridberndsen commented on dev/ppr_tables_bbwp.R
> +    bbwp_measures[!is.na(categories), categories := paste0(categories,"||alles")]
I checked whether all eco_measures have this "alles" tag and that only the eco_measures get this "alles" tag. This was the case. I made the code more clear by changing `!is.na(categories)` into `!is.na(eco_id)`.
For now I changed "alles" into "Ecoregeling_alles", though this does not look that nice in my opinion.

2023-01-20 09:22 UTC, astridberndsen commented on DESCRIPTION
> +Version: 0.10.19
OK

2023-01-20 09:23 UTC, astridberndsen commented on NEWS.md
> +* `bbwp_measures` has extra category `alles` in column `categories` for each Ecoregeling measure
I changed "alles" into "Ecoregeling_alles".

2023-01-20 09:30 UTC, astridberndsen commented on tests/testthat/test-bbwp_check_meas.R
> +    expected = c(157,65),
Twelve rows are removed from bbwp_measures as EG20 is reduced from 18 rows to 6 rows.

2023-01-20 12:06 UTC, gerardhros commented on NEWS.md
> +* `bbwp_measures` has extra category `alles` in column `categories` for each Ecoregeling measure
why not using "Ecoregeling" as a summary term for all of them? Note that this is also the term that will be in the select box in the tool, and "ecoregeling_alles" is not a nice word ... ;-)

2023-01-20 12:08 UTC, gerardhros commented on R/er_meas_scores.R
> +    dt[grepl('^EG20',eco_id) & B_AREA_REL > 7 & B_AREA_REL < 9 & er_total > 0, c(cols.sel) := Map('+',mget(cols.sel),cols.ad1)]
and what happens with the value 9?

2023-01-20 12:09 UTC, gerardhros commented on dev/ppr_tables_bbwp.R
> +    bbwp_measures[!is.na(categories), categories := paste0(categories,"||alles")]
agreed. see my proposal above. just replace by "Ecoregeling"?

2023-01-20 12:18 UTC, astridberndsen commented on R/er_meas_scores.R
> +    dt[grepl('^EG20',eco_id) & B_AREA_REL > 7 & B_AREA_REL < 9 & er_total > 0, c(cols.sel) := Map('+',mget(cols.sel),cols.ad1)]
Values 5, 7 and 9 are now changed into 1, 3, and 5 based on Wouter's request from yesterday evening. 
So this means that when there is a value of exactly 5 (boundary of the highest category) this value is now via `<= 5` set in the second category level (this was `== 5` , but then you would have had a wrong calculation so changed into `<=5`).

2023-01-20 12:22 UTC, astridberndsen commented on NEWS.md
> +* `bbwp_measures` has extra category `alles` in column `categories` for each Ecoregeling measure
Indeed, I changed it into "Ecoregeling". The client requested 'alles' as category and as they are quite picky we have to deal with the possibility that we get some comments on that.

2023-01-20 12:23 UTC, astridberndsen commented on dev/ppr_tables_bbwp.R
> +    bbwp_measures[!is.na(categories), categories := paste0(categories,"||alles")]
Replaced it.

2023-01-20 14:46 UTC, astridberndsen commented on tests/testthat/test-bbwp.R
>        tolerance = 0.01)
I fixed the issue and reverted the tests for bbwp back to orginal. 
The `effect_nue` column of the measures.csv file was read in with some values as "1.166.666.667" instead of 1.17. That is now fixed.

2023-01-20 14:46 UTC, astridberndsen commented on tests/testthat/test-bbwp_field_scores.R
> +      S_BBWP_NUE = c(99,53,100),
See comment above

2023-01-25 10:09 UTC, gerardhros approved these changes

2023-01-25 10:46 UTC, TessaNMI reviewed
Code surrounding EG20 adapted so it will give points contingent on crop categories in DB. Now DB holds all crop categories. Can be adjusted later by client. Corrections are ok.

2023-01-25 10:46 UTC, TessaNMI approved these changes

2023-01-25 11:17 UTC, merged