BBWP 126: use landscape category
AgroCares/BedrijfsBodemWaterPlanCalculator pull request #92
Opened 2024-09-17 21:39 UTC by yuki-nmi

Measure table was updated with new measure scores for water buffering (effect_wb), and landscape-type-specific weighing factor is introduced.
Test functions are updated accordingly.

2024-09-18 11:59 UTC, KeesDoolNMI requested changes
Nice work, a few final questions

2024-09-18 11:59 UTC, KeesDoolNMI commented on DESCRIPTION
> +Version: 2.2.3
This should be version 2.3.0

2024-09-19 07:17 UTC, yuki-nmi commented on DESCRIPTION
> +Version: 2.2.3
Indeed! I changed to 2.3.0, also in NEWS.md

2024-09-19 11:35 UTC, yuki-nmi commented on dev/bbwp_measures2.csv
now the script to make bbwp_measures table is moved to the Github Repo NMI-DATA_scripts. The products of the script is copied to the folder 'dev'

2024-09-19 11:38 UTC, yuki-nmi reviewed
Requested changes were made.

2024-09-23 16:10 UTC, yuki-nmi commented
The syntax of melt function was fixed, so that it is now compatible for data.table 1.16.0.
Further, I found an error in the bbwp_measures.Rd (i.e. a unncessary row-name column was included), so I removed it and updated the test function.

2024-09-24 08:31 UTC, KeesDoolNMI commented
Fantastic! Thanks for the effort 😄

2024-09-24 09:01 UTC, merged